cellexecute:
- execution_count: 0
  pk: 1
- execution_count: 1
  pk: 2
codecells:
- doc_order: 0
  doc_pk: 1
  exec_order: 0
  kernel_pk: 1
  meta_data:
    timeout: 20
  name: null
  pk: 1
  source: 'print("x")

    a = 1

    a'
- doc_order: 1
  doc_pk: 1
  exec_order: 1
  kernel_pk: 1
  meta_data:
    timeout: null
  name: null
  pk: 2
  source: raise ValueError("failed")
documents:
- meta_data: null
  pk: 1
  uri: contents
kernelinfo:
- data:
    kernelspec:
      display_name: Python 3
      language: python
      name: python3
    language_info:
      codemirror_mode:
        name: ipython
        version: 3
      file_extension: .py
      mimetype: text/x-python
      name: python
      nbconvert_exporter: python
      pygments_lexer: ipython3
      version: 3.7.6
  pk: 1
kernels:
- doc_order: 0
  doc_pk: 1
  kernel_type: python3
  meta_data:
    allow_errors: true
  name: null
  pk: 1
mimebundles:
- mimetype: text/plain
  output_pk: 2
  pk: 1
  source: '1'
outputs:
- ename: null
  evalue: null
  execute_pk: 1
  execution_count: null
  meta_data: null
  name: stdout
  order: 0
  output_type: stream
  pk: 1
  text: 'x

    '
  traceback: null
- ename: null
  evalue: null
  execute_pk: 1
  execution_count: 0
  meta_data: {}
  name: null
  order: 1
  output_type: execute_result
  pk: 2
  text: null
  traceback: null
- ename: ValueError
  evalue: failed
  execute_pk: 2
  execution_count: null
  meta_data: null
  name: null
  order: 0
  output_type: error
  pk: 3
  text: null
  traceback:
  - "\e[0;31m---------------------------------------------------------------------------\e\
    [0m"
  - "\e[0;31mValueError\e[0m                                Traceback (most recent\
    \ call last)"
  - "\e[0;32m<ipython-input-2-185ef900d1e6>\e[0m in \e[0;36m<module>\e[0;34m\e[0m\n\
    \e[0;32m----> 1\e[0;31m \e[0;32mraise\e[0m \e[0mValueError\e[0m\e[0;34m(\e[0m\e\
    [0;34m\"failed\"\e[0m\e[0;34m)\e[0m\e[0;34m\e[0m\e[0;34m\e[0m\e[0m\n\e[0m"
  - "\e[0;31mValueError\e[0m: failed"
